version: '3.3'

#  millionaire $ netstat -a -n | grep "LIST"
#  tcp4       0      0  127.0.0.1.55380        *.*                    LISTEN
#  tcp4       0      0  127.0.0.1.39624        *.*                    LISTEN
#  tcp4       0      0  127.0.0.1.55350        *.*                    LISTEN
#  tcp4       0      0  127.0.0.1.26380        *.*                    LISTEN
#  tcp4       0      0  127.0.0.1.26379        *.*                    LISTEN
#  tcp4       0      0  127.0.0.1.6380         *.*                    LISTEN
#  tcp4       0      0  127.0.0.1.6379         *.*                    LISTEN
#  tcp4       0      0  127.0.0.1.54246        *.*                    LISTEN
#  tcp4       0      0  127.0.0.1.54247        *.*                    LISTEN
#  tcp46      0      0  *.53741                *.*                    LISTEN
#  tcp4       0      0  127.0.0.1.63342        *.*                    LISTEN
#  tcp4       0      0  127.0.0.1.6942         *.*                    LISTEN

#  root@0fedc9edd30e:/data# redis-cli --version
#  redis-cli 7.0.11
services:

  ## http://dmitrypol.github.io/redis/2020/10/01/redis-sentinel.html
  redis-master:
    image: redis
    container_name: redis-master
    ports:
      - "6379:6379"
    networks:
      vpnet:
        ipv4_address: 172.25.0.11
    cpus: "0.5"
    mem_reservation: "128M"
    mem_limit: "256M"

  redis-slave:
    image: redis
    container_name: redis-slave
    command: redis-server --port 6380 --slaveof redis-master 6379
    links:
      - redis-master
    ports:
      - "6380:6380"
    networks:
      vpnet:
        ipv4_address: 172.25.0.12
    cpus: "0.5"
    mem_reservation: "128M"
    mem_limit: "256M"

  redis-sentinel1:
    container_name: redis-sentinel1
    build:
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - "26379:26379"
    networks:
      vpnet:
        ipv4_address: 172.25.0.13
    cpus: "0.5"
    mem_reservation: "128M"
    mem_limit: "256M"

  redis-sentinel2:
    container_name: redis-sentinel2
    build:
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - "26380:26379"
    networks:
      vpnet:
        ipv4_address: 172.25.0.14
    cpus: "0.5"
    mem_reservation: "128M"
    mem_limit: "256M"

  cache-vista-app:
    container_name: cache-vista
    build:
      context: .
    depends_on:
      - redis-master
      - redis-sentinel1
      - redis-sentinel2
    links:
      - redis-master
      - redis-sentinel1
      - redis-sentinel2
    networks:
      vpnet:
        ipv4_address: 172.25.0.15
    cpus: "0.5"
    mem_reservation: "184M"
    mem_limit: "512M"
## docker-compose 3
#    resources:
#      limits:
#        cpus: 1
#        memory: 786m
#      reservations:
#        cpus: 0.5
#        memory: 150m

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    cpus: "0.5"
    mem_reservation: "50M"
    mem_limit: "512M"

networks:
  vpnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
#          gateway: 172.25.0.1