version: '3.3'

services:

  #  volumes:
    #    redis_data:
      ##    redis_conf:
  redis:
    image: redis
    container_name: redis_server
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass password
      #    volumes:
      #      - redis_data:/data/node-redis/redis-data
        #      - redis_conf:/data/node-redis/redis.conf

  memcached:
    image: memcached:latest
    ports:
      - 11211:11211
