version: '3.3'

services:

## http://dmitrypol.github.io/redis/2020/10/01/redis-sentinel.html

  redis-master:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - shared_network

  redis-slave:
    image: redis
    command: >
      bash -c "echo 'port 6380' > slave.conf &&
      echo 'replicaof 0.0.0.0 6379' >> slave.conf &&
      cat slave.conf &&
      redis-server slave.conf"
#    links:
#      - redis-master
    ports:
      - 6380:6380
    networks:
      - shared_network

  redis-sentinel:
    image: redis
    command: >
      bash -c "echo 'port 26379' > sentinel.conf &&
      echo 'dir /tmp' >> sentinel.conf &&
      echo 'sentinel monitor mymaster 0.0.0.0 6379 2' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 5000' >> sentinel.conf &&
      cat sentinel.conf &&
      redis-server sentinel.conf --sentinel"
#    links:
##      - redis-master
###      - redis-slave
    ports:
      - 26379:26379
    networks:
      - shared_network

  redis-sentinel1:
    image: redis
    command: >
      bash -c "echo 'port 26380' > sentinel.conf &&
      echo 'dir /tmp' >> sentinel.conf &&
      echo 'sentinel monitor mymaster 0.0.0.0 6379 2' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 5000' >> sentinel.conf &&
      cat sentinel.conf &&
      redis-server sentinel.conf --sentinel"
#    links:
#      - redis-master
##      - redis-slave
    ports:
      - 26380:26380
    networks:
      - shared_network

#  memcached:
#    image: memcached:latest
#    ports:
#      - 11211:11211

networks:
  shared_network: {}