version: '3.3'

services:

## http://dmitrypol.github.io/redis/2020/10/01/redis-sentinel.html
  redis-master:
    image: redis
    container_name: redis-master
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      vpnet:
        ipv4_address: 172.25.0.11

  redis-slave:
    image: redis
    container_name: redis-slave
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    expose:
      - 6380
    ports:
      - 6380:6380
    networks:
      vpnet:
        ipv4_address: 172.25.0.12

  redis-sentinel1:
    image: redis
    container_name: redis-sentinel1
    build:
      context: ./redis-sentinel
    links:
      - redis-master
    expose:
      - 26379
    ports:
      - 26379:26379
    networks:
      vpnet:
        ipv4_address: 172.25.0.13

  redis-sentinel2:
    image: redis
    container_name: redis-sentinel2
    build:
      context: ./redis-sentinel
    links:
      - redis-master
    expose:
      - 26380
    ports:
      - 26380:26379
    networks:
      vpnet:
        ipv4_address: 172.25.0.14

#  memcached:
#    image: memcached:latest
#    ports:
#      - 11211:11211

  cache-vista-app:
    build:
      context: .
    depends_on:
      - redis-master
      - redis-sentinel1
      - redis-sentinel2
    links:
      - redis-master
      - redis-sentinel1
      - redis-sentinel2
    networks:
      vpnet:
        ipv4_address: 172.25.0.15

networks:
  vpnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1